/**
 * Inventria Mock Enterprise Datasets
 * Pre-populated with realistic inventory, warehouse, order, and supplier records in INR (₹).
 */

export const MOCK_SUMMARY_STATS = {
  totalProducts: 1482,
  totalWarehouses: 12,
  totalSuppliers: 48,
  lowStockProducts: 19,
  todaysSales: 248500.75,
  monthlyRevenue: 3429000.00,
  salesGrowthPct: 14.8,
  inventoryValue: 18504000.00,
};

export const MOCK_CATEGORIES = [
  { id: 'CAT-001', name: 'Electronics & Components', code: 'ELEC', description: 'Microcontrollers, sensors, ICs, and circuit boards', productCount: 412, icon: 'Cpu' },
  { id: 'CAT-002', name: 'Industrial Hardware', code: 'HDWR', description: 'Fasteners, valves, bearings, and heavy fittings', productCount: 320, icon: 'Wrench' },
  { id: 'CAT-003', name: 'Packaging & Logistics', code: 'PACK', description: 'Corrugated boxes, pallets, bubble wraps, and straps', productCount: 215, icon: 'Package' },
  { id: 'CAT-004', name: 'Raw Materials', code: 'RAWM', description: 'Aluminium ingots, copper coils, synthetic resins', productCount: 185, icon: 'Layers' },
  { id: 'CAT-005', name: 'Safety & PPE Equipment', code: 'SAFE', description: 'Helmets, safety goggles, gloves, high-vis vests', productCount: 190, icon: 'Shield' },
  { id: 'CAT-006', name: 'Office Supplies & Tech', code: 'OFFC', description: 'Enterprise monitors, ergonomic desks, accessories', productCount: 160, icon: 'Monitor' },
];

export const MOCK_PRODUCTS = [
  {
    id: 'PRD-1001',
    name: 'High-Torque Stepper Motor NEMA 23',
    sku: 'MOT-NEMA23-01',
    category: 'Electronics & Components',
    price: 3850.00,
    cost: 2100.00,
    stockQuantity: 420,
    minStockThreshold: 50,
    warehouse: 'Main Central Hub (WH-01)',
    location: 'Aisle 4, Shelf B2',
    supplier: 'Apex Automation Corp',
    status: 'In Stock',
    lastUpdated: '2026-08-04',
  },
  {
    id: 'PRD-1002',
    name: 'Precision Stainless Steel Ball Bearing 6204-2RS',
    sku: 'BRG-6204-SS',
    category: 'Industrial Hardware',
    price: 990.00,
    cost: 450.00,
    stockQuantity: 18,
    minStockThreshold: 40,
    warehouse: 'East Coast Distribution (WH-02)',
    location: 'Aisle 12, Bin 104',
    supplier: 'Titanium Engineering Inc',
    status: 'Low Stock',
    lastUpdated: '2026-08-05',
  },
  {
    id: 'PRD-1003',
    name: 'Industrial Heavy Duty Pallet Wrap 20 Micron (6 Pack)',
    sku: 'PKG-WRAP-20M',
    category: 'Packaging & Logistics',
    price: 6890.00,
    cost: 3800.00,
    stockQuantity: 145,
    minStockThreshold: 30,
    warehouse: 'Midwest Logistics Center (WH-03)',
    location: 'Aisle 1, Bay A',
    supplier: 'Global Packaging Solutions',
    status: 'In Stock',
    lastUpdated: '2026-08-02',
  },
  {
    id: 'PRD-1004',
    name: 'Industrial Safety Helmet Type II High Visibility',
    sku: 'PPE-HLM-HV2',
    category: 'Safety & PPE Equipment',
    price: 2499.00,
    cost: 1250.00,
    stockQuantity: 0,
    minStockThreshold: 25,
    warehouse: 'Main Central Hub (WH-01)',
    location: 'Aisle 8, Shelf C1',
    supplier: 'SafeGuard Pro Equipment',
    status: 'Out of Stock',
    lastUpdated: '2026-08-06',
  },
  {
    id: 'PRD-1005',
    name: 'Armored Copper Cable 4-Core 16mm (100m Roll)',
    sku: 'CBL-COP-4C16',
    category: 'Raw Materials',
    price: 24500.00,
    cost: 16500.00,
    stockQuantity: 64,
    minStockThreshold: 20,
    warehouse: 'Southern Storage Annex (WH-04)',
    location: 'Heavy Storage Zone D',
    supplier: 'Metals & Wire Direct',
    status: 'In Stock',
    lastUpdated: '2026-08-01',
  },
  {
    id: 'PRD-1006',
    name: 'Microcontroller Dev Board Cortex-M4 Dual Core',
    sku: 'MCU-CM4-DUAL',
    category: 'Electronics & Components',
    price: 1850.00,
    cost: 920.00,
    stockQuantity: 12,
    minStockThreshold: 30,
    warehouse: 'Pacific Northwest Warehouse (WH-05)',
    location: 'Cleanroom Rack 3',
    supplier: 'Apex Automation Corp',
    status: 'Low Stock',
    lastUpdated: '2026-08-05',
  },
  {
    id: 'PRD-1007',
    name: 'Pneumatic Control Valve 5/2 Way 24V DC',
    sku: 'VLV-PNM-52W',
    category: 'Industrial Hardware',
    price: 4950.00,
    cost: 2600.00,
    stockQuantity: 280,
    minStockThreshold: 40,
    warehouse: 'East Coast Distribution (WH-02)',
    location: 'Aisle 6, Bin 50',
    supplier: 'Titanium Engineering Inc',
    status: 'In Stock',
    lastUpdated: '2026-08-03',
  },
  {
    id: 'PRD-1008',
    name: 'Ultra-Wide 34-inch Curved Workstation Monitor',
    sku: 'OFF-MON-34C',
    category: 'Office Supplies & Tech',
    price: 38900.00,
    cost: 25000.00,
    stockQuantity: 8,
    minStockThreshold: 10,
    warehouse: 'Main Central Hub (WH-01)',
    location: 'IT Storage Annex',
    supplier: 'NexTech Systems',
    status: 'Low Stock',
    lastUpdated: '2026-08-04',
  },
];

export const MOCK_WAREHOUSES = [
  {
    id: 'WH-01',
    name: 'Main Central Hub (Mumbai)',
    code: 'HUB-BOM',
    location: 'Mumbai, MH',
    address: 'Plot 45, MIDC Industrial Area, Andheri East, Mumbai, MH 400093',
    manager: 'Sarah Jenkins',
    contactEmail: 's.jenkins@inventria.io',
    contactPhone: '+91 98200 12345',
    capacityTotal: 50000,
    currentStock: 41200,
    utilizationPct: 82.4,
    status: 'Active',
    health: 'Healthy',
  },
  {
    id: 'WH-02',
    name: 'East Coast Hub (Bengaluru)',
    code: 'DIST-BLR',
    location: 'Bengaluru, KA',
    address: '88 Electronics City Phase 1, Hosur Road, Bengaluru, KA 560100',
    manager: 'David Miller',
    contactEmail: 'd.miller@inventria.io',
    contactPhone: '+91 98450 67890',
    capacityTotal: 35000,
    currentStock: 32100,
    utilizationPct: 91.7,
    status: 'Active',
    health: 'Near Capacity',
  },
  {
    id: 'WH-03',
    name: 'North Logistics Hub (Delhi NCR)',
    code: 'DEPOT-DEL',
    location: 'Gurugram, HR',
    address: '500 Cargo Logistics Park, NH-8, Gurugram, HR 122001',
    manager: 'Robert Vance',
    contactEmail: 'r.vance@inventria.io',
    contactPhone: '+91 98110 54321',
    capacityTotal: 40000,
    currentStock: 24500,
    utilizationPct: 61.25,
    status: 'Active',
    health: 'Healthy',
  },
  {
    id: 'WH-04',
    name: 'West Storage Annex (Pune)',
    code: 'ANNEX-PUNE',
    location: 'Pune, MH',
    address: '77 Chakan Industrial Zone, Phase II, Pune, MH 410501',
    manager: 'Elena Rodriguez',
    contactEmail: 'e.rodriguez@inventria.io',
    contactPhone: '+91 98220 99887',
    capacityTotal: 30000,
    currentStock: 18900,
    utilizationPct: 63.0,
    status: 'Active',
    health: 'Healthy',
  },
  {
    id: 'WH-05',
    name: 'South Logistics Hub (Chennai)',
    code: 'WH-MAA',
    location: 'Chennai, TN',
    address: '1200 Sriperumbudur Industrial Corridor, Chennai, TN 602105',
    manager: 'Alex Thorne',
    contactEmail: 'a.thorne@inventria.io',
    contactPhone: '+91 98400 11223',
    capacityTotal: 25000,
    currentStock: 24100,
    utilizationPct: 96.4,
    status: 'Active',
    health: 'Over Capacity',
  },
];

export const MOCK_SUPPLIERS = [
  {
    id: 'SUP-001',
    name: 'Apex Automation Corp',
    contactPerson: 'Marcus Sterling',
    email: 'm.sterling@apexauto.com',
    phone: '+91 22 5550 9011',
    address: '100 Tech Park, San Jose, CA / Mumbai Office',
    categories: ['Electronics & Components'],
    rating: 4.9,
    status: 'Active',
    totalOrders: 64,
  },
  {
    id: 'SUP-002',
    name: 'Titanium Engineering Inc',
    contactPerson: 'Helena Berg',
    email: 'hberg@titaniumeng.com',
    phone: '+91 80 5550 3420',
    address: '45 Metallurgy Road, Peenya, Bengaluru',
    categories: ['Industrial Hardware'],
    rating: 4.7,
    status: 'Active',
    totalOrders: 42,
  },
  {
    id: 'SUP-003',
    name: 'Global Packaging Solutions',
    contactPerson: 'Jason Thorne',
    email: 'j.thorne@globalpack.com',
    phone: '+91 44 5550 8833',
    address: '90 Paper Mill Rd, Sriperumbudur, Chennai',
    categories: ['Packaging & Logistics'],
    rating: 4.8,
    status: 'Active',
    totalOrders: 89,
  },
  {
    id: 'SUP-004',
    name: 'SafeGuard Pro Equipment',
    contactPerson: 'Claire Bennett',
    email: 'c.bennett@safeguardpro.com',
    phone: '+91 124 555 1200',
    address: '320 Armor Zone, Manesar, Haryana',
    categories: ['Safety & PPE Equipment'],
    rating: 4.5,
    status: 'Active',
    totalOrders: 31,
  },
  {
    id: 'SUP-005',
    name: 'Metals & Wire Direct',
    contactPerson: 'Gary O\'Connor',
    email: 'g.oconnor@metalswire.com',
    phone: '+91 20 5550 4389',
    address: '77 Industrial Estate, Bhosari, Pune',
    categories: ['Raw Materials'],
    rating: 4.6,
    status: 'Active',
    totalOrders: 55,
  },
];

export const MOCK_CUSTOMERS = [
  {
    id: 'CUST-101',
    name: 'Tata Motors Supply Chain',
    company: 'Tata Motors Limited',
    email: 'procurement@tatamotors.com',
    phone: '+91 22 6656 8700',
    address: 'Bombay House, 24 Homi Mody Street, Mumbai, MH 400001',
    totalOrders: 28,
    totalSpent: 4859000.00,
    status: 'Active',
  },
  {
    id: 'CUST-102',
    name: 'Reliance Logistics & Retail',
    company: 'Reliance Industries Ltd',
    email: 'vendor-orders@ril.com',
    phone: '+91 22 3555 5000',
    address: 'Maker Chambers IV, Nariman Point, Mumbai, MH 400021',
    totalOrders: 19,
    totalSpent: 3204500.50,
    status: 'Active',
  },
  {
    id: 'CUST-103',
    name: 'Mahindra Defense & Aerospace',
    company: 'Mahindra & Mahindra Ltd',
    email: 'defense-inbound@mahindra.com',
    phone: '+91 22 2846 8500',
    address: 'Gateway Building, Apollo Bunder, Mumbai, MH 400001',
    totalOrders: 112,
    totalSpent: 12940000.00,
    status: 'Active',
  },
  {
    id: 'CUST-104',
    name: 'L&T Heavy Engineering',
    company: 'Larsen & Toubro Ltd',
    email: 'parts@larsentoubro.com',
    phone: '+91 22 6752 5656',
    address: 'L&T House, Ballard Estate, Mumbai, MH 400001',
    totalOrders: 14,
    totalSpent: 1842000.00,
    status: 'Active',
  },
];

export const MOCK_PURCHASE_ORDERS = [
  {
    id: 'PO-2026-001',
    supplier: 'Apex Automation Corp',
    warehouse: 'Main Central Hub (WH-01)',
    orderDate: '2026-08-01',
    expectedDelivery: '2026-08-10',
    totalAmount: 1845000.00,
    itemsCount: 4,
    status: 'Approved',
    createdByName: 'John Doe (Manager)',
    items: [
      { name: 'High-Torque Stepper Motor NEMA 23', quantity: 200, unitPrice: 2100.00, total: 420000.00 },
      { name: 'Microcontroller Dev Board Cortex-M4 Dual Core', quantity: 500, unitPrice: 920.00, total: 460000.00 },
      { name: 'Precision Encoder Module 1024 PPR', quantity: 300, unitPrice: 3216.66, total: 965000.00 },
    ],
  },
  {
    id: 'PO-2026-002',
    supplier: 'Titanium Engineering Inc',
    warehouse: 'East Coast Distribution (WH-02)',
    orderDate: '2026-08-03',
    expectedDelivery: '2026-08-12',
    totalAmount: 842050.00,
    itemsCount: 2,
    status: 'Pending',
    createdByName: 'John Doe (Manager)',
    items: [
      { name: 'Precision Stainless Steel Ball Bearing 6204-2RS', quantity: 500, unitPrice: 450.00, total: 225000.00 },
      { name: 'Pneumatic Control Valve 5/2 Way 24V DC', quantity: 237, unitPrice: 2603.58, total: 617050.00 },
    ],
  },
  {
    id: 'PO-2026-003',
    supplier: 'SafeGuard Pro Equipment',
    warehouse: 'Main Central Hub (WH-01)',
    orderDate: '2026-08-05',
    expectedDelivery: '2026-08-09',
    totalAmount: 495000.00,
    itemsCount: 1,
    status: 'Received',
    createdByName: 'Sarah Jenkins',
    items: [
      { name: 'Industrial Safety Helmet Type II High Visibility', quantity: 300, unitPrice: 1650.00, total: 495000.00 },
    ],
  },
];

export const MOCK_SALES_ORDERS = [
  {
    id: 'SO-2026-8801',
    customerName: 'Tata Motors Supply Chain',
    customerCompany: 'Tata Motors Limited',
    orderDate: '2026-08-04',
    deliveryDate: '2026-08-08',
    totalAmount: 3420000.00,
    itemsCount: 3,
    status: 'Delivered',
    paymentStatus: 'Paid',
    shippingAddress: 'Plot 45, Chinchwad Industrial Estate, Pune, MH 411019',
    items: [
      { name: 'High-Torque Stepper Motor NEMA 23', sku: 'MOT-NEMA23-01', quantity: 400, unitPrice: 3850.00, total: 1540000.00 },
      { name: 'Pneumatic Control Valve 5/2 Way 24V DC', sku: 'VLV-PNM-52W', quantity: 300, unitPrice: 4950.00, total: 1485000.00 },
      { name: 'Industrial Heavy Duty Pallet Wrap', sku: 'PKG-WRAP-20M', quantity: 57, unitPrice: 6930.00, total: 395000.00 },
    ],
  },
  {
    id: 'SO-2026-8802',
    customerName: 'Reliance Logistics & Retail',
    customerCompany: 'Reliance Industries Ltd',
    orderDate: '2026-08-05',
    deliveryDate: '2026-08-11',
    totalAmount: 1890000.00,
    itemsCount: 2,
    status: 'Processing',
    paymentStatus: 'Pending',
    shippingAddress: 'Maker Chambers IV, Nariman Point, Mumbai, MH 400021',
    items: [
      { name: 'Armored Copper Cable 4-Core 16mm (100m Roll)', sku: 'CBL-COP-4C16', quantity: 70, unitPrice: 24500.00, total: 1715000.00 },
      { name: 'Precision Stainless Steel Ball Bearing', sku: 'BRG-6204-SS', quantity: 176, unitPrice: 994.31, total: 175000.00 },
    ],
  },
  {
    id: 'SO-2026-8803',
    customerName: 'Mahindra Defense & Aerospace',
    customerCompany: 'Mahindra & Mahindra Ltd',
    orderDate: '2026-08-06',
    deliveryDate: '2026-08-12',
    totalAmount: 4450000.00,
    itemsCount: 1,
    status: 'Shipped',
    paymentStatus: 'Paid',
    shippingAddress: 'Gateway Building, Apollo Bunder, Mumbai, MH 400001',
    items: [
      { name: 'Industrial Heavy Duty Pallet Wrap 20 Micron (6 Pack)', sku: 'PKG-WRAP-20M', quantity: 645, unitPrice: 6899.22, total: 4450000.00 },
    ],
  },
];

export const MOCK_NOTIFICATIONS = [
  { id: 1, title: 'Low Stock Alert', message: 'Precision Stainless Steel Ball Bearing (18 items remaining)', time: '10 mins ago', read: false, type: 'warning' },
  { id: 2, title: 'New PO Approved', message: 'PO-2026-001 has been approved by John Doe', time: '1 hour ago', read: false, type: 'info' },
  { id: 3, title: 'Shipment Delivered', message: 'SO-2026-8801 delivered to Tata Motors Supply Chain', time: '3 hours ago', read: true, type: 'success' },
];

export const MOCK_CHART_DATA = {
  monthlySales: {
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
    revenue: [1800000, 2200000, 2100000, 2750000, 3100000, 2950000, 3280000, 3429000],
    expenses: [1400000, 1650000, 1500000, 1950000, 2100000, 2050000, 2250000, 2380000],
  },
  categoryDistribution: {
    labels: ['Electronics', 'Hardware', 'Packaging', 'Raw Materials', 'Safety & PPE', 'Office Tech'],
    data: [412, 320, 215, 185, 190, 160],
  },
  warehouseCapacity: {
    labels: ['Main Mumbai', 'East Bengaluru', 'North Delhi NCR', 'West Pune', 'South Chennai'],
    capacity: [50000, 35000, 40000, 30000, 25000],
    used: [41200, 32100, 24500, 18900, 24100],
  },
};
